basePath: /api/v1/
definitions:
  dtos.AppLogDto:
    properties:
      actionID:
        type: string
      createdAt:
        type: string
      id:
        type: string
      level:
        description: Level - level of the log
        type: string
      message:
        description: Message - log message
        type: string
      source:
        description: Source - method from which the log was obtained
        type: string
    type: object
  dtos.DtoType:
    type: object
  dtos.EthernetSwitchCreateDto:
    properties:
      address:
        description: Address - switch ip address
        type: string
      name:
        description: Name - switch name
        type: string
      password:
        description: Password - ethernet switch management password
        type: string
      serial:
        description: Serial - switch serial number
        type: string
      switchModel:
        description: SwitchModel - switch model
        type: integer
      username:
        description: Username - switch admin username
        type: string
    type: object
  dtos.EthernetSwitchDto:
    properties:
      address:
        description: Address - switch ip address
        type: string
      createdAt:
        description: CreatedAt - entity create time
        type: string
      id:
        description: Id - unique identifier
        type: string
      name:
        description: Name - switch name
        type: string
      serial:
        description: Serial - switch serial number
        type: string
      switchModel:
        description: SwitchModel - switch model
        type: integer
      updatedAt:
        description: UpdatedAt - entity update time
        type: string
      username:
        description: Username - switch admin username
        type: string
    type: object
  dtos.EthernetSwitchUpdateDto:
    properties:
      address:
        description: Address - switch ip address
        type: string
      name:
        description: Name - switch name
        type: string
      password:
        description: Password - ethernet switch management password
        type: string
      serial:
        description: Serial - switch serial number
        type: string
      switchModel:
        description: SwitchModel - switch model
        type: integer
      username:
        description: Username - switch admin username
        type: string
    type: object
  dtos.HttpLogDto:
    properties:
      clientIP:
        description: ClientIP - client IP address
        type: string
      createdAt:
        type: string
      customRequestHeaders:
        description: CustomRequestHeaders - custom headers of the request
        type: string
      domain:
        description: Domain - domain that processed the request
        type: string
      httpMethod:
        description: HttpMethod - http method
        type: string
      id:
        type: string
      latency:
        description: Latency - latency in milliseconds
        type: integer
      queryParams:
        description: QueryParams - query params passed
        type: string
      relativePath:
        description: RelativePath - path to the endpoint
        type: string
      requestBody:
        description: RequestBody - body of the request
        type: string
      requestHeaders:
        description: RequestHeaders - headers of the request
        type: string
      responseBody:
        description: ResponseBody - body of the response
        type: string
    type: object
  dtos.PaginatedListDto:
    properties:
      items:
        description: Items - array of DTO items
        items:
          $ref: '#/definitions/dtos.DtoType'
        type: array
      page:
        description: Page - page number
        type: integer
      size:
        description: Size - page size
        type: integer
      total:
        description: Total - total number of items
        type: integer
    type: object
  dtos.ResponseDataDto:
    properties:
      data:
        description: Data - any data to send
      status:
        $ref: '#/definitions/dtos.ResponseStatusDto'
        description: Status - response status structure
    type: object
  dtos.ResponseDto:
    properties:
      status:
        $ref: '#/definitions/dtos.ResponseStatusDto'
        description: Status - response status structure
    type: object
  dtos.ResponseStatusDto:
    properties:
      code:
        description: Code - 0 if OK, otherwise 1
        type: integer
      message:
        description: Message - response message
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API supporter
    url: http://www.swagger.io/support
  description: Description of specifications
  license:
    name: license(Mandatory)
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Rack of labs API
  version: version(1.0)
paths:
  /log/app/:
    get:
      consumes:
      - application/json
      parameters:
      - description: Order by field
        in: path
        name: orderBy
        type: string
      - description: '''asc'' or ''desc'' for ascending or descending order'
        in: path
        name: orderDirection
        type: string
      - description: searchable value in entity
        in: path
        name: search
        type: string
      - description: page number
        in: path
        name: page
        type: integer
      - description: number of entities per page
        in: path
        name: pageSize
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/dtos.ResponseDataDto'
            - properties:
                data:
                  allOf:
                  - $ref: '#/definitions/dtos.PaginatedListDto'
                  - properties:
                      items:
                        items:
                          $ref: '#/definitions/dtos.AppLogDto'
                        type: array
                    type: object
              type: object
      summary: Gets paginated list of app logs
      tags:
      - app log
  /log/app/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: log id
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/dtos.ResponseDataDto'
            - properties:
                data:
                  $ref: '#/definitions/dtos.AppLogDto'
              type: object
      summary: Gets http app by id
      tags:
      - app log
  /log/http/:
    get:
      consumes:
      - application/json
      parameters:
      - description: Order by field
        in: path
        name: orderBy
        type: string
      - description: '''asc'' or ''desc'' for ascending or descending order'
        in: path
        name: orderDirection
        type: string
      - description: searchable value in entity
        in: path
        name: search
        type: string
      - description: page number
        in: path
        name: page
        type: integer
      - description: number of entities per page
        in: path
        name: pageSize
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            allOf:
            - $ref: '#/definitions/dtos.ResponseDataDto'
            - properties:
                data:
                  allOf:
                  - $ref: '#/definitions/dtos.PaginatedListDto'
                  - properties:
                      items:
                        items:
                          $ref: '#/definitions/dtos.HttpLogDto'
                        type: array
                    type: object
              type: object
      summary: Gets paginated list of http logs
      tags:
      - http log
  /log/http/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: log id
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/dtos.ResponseDataDto'
            - properties:
                data:
                  $ref: '#/definitions/dtos.HttpLogDto'
              type: object
      summary: Gets http log by id
      tags:
      - http log
  /switch/:
    get:
      consumes:
      - application/json
      parameters:
      - description: Order by field
        in: path
        name: orderBy
        type: string
      - description: '''asc'' or ''desc'' for ascending or descending order'
        in: path
        name: orderDirection
        type: string
      - description: searchable value in entity
        in: path
        name: search
        type: string
      - description: page number
        in: path
        name: page
        type: integer
      - description: number of entities per page
        in: path
        name: pageSize
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            allOf:
            - $ref: '#/definitions/dtos.ResponseDataDto'
            - properties:
                data:
                  allOf:
                  - $ref: '#/definitions/dtos.PaginatedListDto'
                  - properties:
                      items:
                        items:
                          $ref: '#/definitions/dtos.EthernetSwitchDto'
                        type: array
                    type: object
              type: object
      summary: Gets paginated list of switches
      tags:
      - ethernet switch
    post:
      consumes:
      - application/json
      parameters:
      - description: ethernet switch fields
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dtos.EthernetSwitchCreateDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.ResponseDataDto'
      summary: Creates new ethernet switch
      tags:
      - ethernet switch
  /switch/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: ethernet switch id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.ResponseDto'
      summary: Delete ethernet switch by id
      tags:
      - ethernet switch
    get:
      consumes:
      - application/json
      parameters:
      - description: ethernet switch id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/dtos.ResponseDataDto'
            - properties:
                data:
                  $ref: '#/definitions/dtos.EthernetSwitchDto'
              type: object
      summary: Gets ethernet switch by id
      tags:
      - ethernet switch
    put:
      consumes:
      - application/json
      parameters:
      - description: ethernet switch fields
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dtos.EthernetSwitchUpdateDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.ResponseDto'
      summary: Updates ethernet switch by id
      tags:
      - ethernet switch
swagger: "2.0"
