---
run:
  timeout: 30m
linters:
  disable:
    - gosimple      # disabled because of go1.18. https://github.com/golangci/golangci-lint/issues/2649
    - staticcheck   # disabled because of go1.18. https://github.com/golangci/golangci-lint/issues/2649
    - structcheck   # disabled because of go1.18. https://github.com/golangci/golangci-lint/issues/2649
    - unused        # disabled because of go1.18. https://github.com/golangci/golangci-lint/issues/2649
