---
name: Unit tests
on:  # yamllint disable-line rule:truthy
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.18.x]
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v3
      - name: Build tests
        run: cd src && go test -c rol/tests -o ./tests/rol.test
      - name: Setup CAP_NET_ADMIN for compiled tests
        if: matrix.os == 'ubuntu-22.04'
        run: |
          sudo setcap cap_net_admin+ep ./src/tests/rol.test
      - name: Run tests
        run: |
          cd src/tests && ./rol.test -test.v
