---
name: Unit tests
on:  # yamllint disable-line rule:truthy
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup packages
        run: |
          sudo apt update
          sudo apt install -y golang
      - uses: actions/checkout@v3
      - run: cd src && sudo go test -v ./tests
