@startuml Project

!include Entity.puml

package domain {
    class Project {
        Name string
        --
        BridgeName string
        --
        Subnet string
    }
    Project -down-* Entity
}

@enduml
